#server:
#    port: 8080
#    servlet:
#        context-path: /api

datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iot
    username: root
    password: 011226
